FROM tomcat:9-jdk17

RUN apt update
RUN apt install unzip zip

ARG version
ENV build_version $version

# Find instructions here: https://backstage.forgerock.com/docs/am/7.5/eval-guide/step-2-deploy-am.html

# We do not want to keep the default applications, remove them
#
RUN rm -rf /usr/local/tomcat/webapps/*

# Setting permissions as instructed by ForgeRock
#
RUN chmod 644 $JAVA_HOME/lib/security/cacerts

# Adding PingAM
#
COPY products/pingam/$build_version /tmp/openam.war
RUN unzip -a /tmp/openam.war -d /usr/local/tomcat/webapps/openam

# Create directory for holding SSL keys
#
RUN mkdir /usr/local/tomcat/ssl

# create non-priviliged user (with its own group) to run tomcat
#
RUN addgroup tomcat
RUN adduser --ingroup tomcat tomcat
RUN chown -R tomcat:tomcat /usr/local/tomcat/

# Copy the server.xml file that uses SSL and the entrypoint script that updates the file with configured hostname and port
#
COPY docker-build/add-ons/openam/usr/local/tomcat/conf/server.xml /usr/local/tomcat/conf/server.xml
COPY docker-build/add-ons/openam/opt/docker/entrypoint.sh /opt/docker/entrypoint.sh

COPY dev/pubCert.crt /tmp/pubCert.crt

RUN keytool -importcert \
    -alias pubCert \
    -file /tmp/pubCert.crt \
    -storepass changeit \
    -keystore $JAVA_HOME/lib/security/cacerts \
    -trustcacerts \
    -noprompt

RUN rm -f /tmp/pubCert.crt

CMD ["/opt/docker/entrypoint.sh"]