FROM webinar/tomcat:10

ARG version
ENV build_version=$version

# Adding PingAM
#
COPY products/pingam/$build_version /tmp/openam.war
RUN unzip -a /tmp/openam.war -d /usr/local/tomcat/webapps/openam

# create non-priviliged user (with its own group) to run tomcat
#
RUN addgroup tomcat
RUN adduser --ingroup tomcat tomcat
RUN chown -R tomcat:tomcat /usr/local/tomcat/

# Copy the server.xml file that uses SSL and the entrypoint script that updates the file with configured hostname and port
#
COPY docker-build/add-ons/openam/usr/local/tomcat/conf/server.xml /usr/local/tomcat/conf/server.xml
COPY docker-build/add-ons/openam/opt/docker/entrypoint.sh /opt/docker/entrypoint.sh

CMD ["/opt/docker/entrypoint.sh"]