FROM webinar/openjdk:17

ARG version
ARG deploymentid
ARG deploymentpwd
ARG hostname
ARG sslpwd
ARG truststorepwd

ENV build_version=$version
ENV deployment_id=$deploymentid
ENV deployment_pwd=$deploymentpwd
ENV local_hostname=$hostname
ENV ssl_pwd=$sslpwd
ENV truststore_pwd=$truststorepwd

COPY products/pingds/$build_version /tmp/opendj.zip

RUN unzip -d /tmp -a /tmp/opendj.zip

RUN mv /tmp/opendj /opt/opendj
RUN rm /tmp/opendj.zip

COPY dev/tlskey.p12 /opt/ssl/tlskey.p12
RUN chmod 644 /opt/ssl/tlskey.p12

#RUN /opt/opendj/bin/dskeymgr create-deployment-id --deploymentIdPassword $deploymentid > DEPLOYMENT_PASSWORD

# More info on setup:
# - https://backstage.forgerock.com/docs/ds/8/install-guide/profile-am-config.html
# - https://docs.pingidentity.com/pingds/8/install-guide/setup-parameters.html
#
RUN /opt/opendj/setup \
    --instancePath /opt/opendj \
    --deploymentId $deployment_id \
    --deploymentIdPassword $deployment_pwd \
    --hostname $local_hostname \
    --rootUserDN uid=admin \
    --rootUserPassword Password1 \
    --monitorUserDn uid=monitor \
    --monitorUserPassword Password1 \
    --adminConnectorPort 4444 \
    --ldapsPort 50636 \
    --httpsPort 8452 \
    --enableStartTls \
    --profile am-config \
    --set am-config/amConfigAdminPassword:Password1 \
    --profile am-cts \
    --set am-cts/amCtsAdminPassword:Password1 \
    --profile am-identity-store \
    --set am-identity-store/amIdentityStoreAdminPassword:Password1 \
    --usePkcs12KeyStore /opt/ssl/tlskey.p12 \
    --keyStorePassword:env ssl_pwd \
    --certNickname tlskey \
    --usePkcs12TrustStore $JAVA_HOME/lib/security/cacerts \
    --trustStorePassword:env truststore_pwd \
    --acceptLicense

WORKDIR /opt/opendj

CMD ["/opt/opendj/bin/start-ds", "--nodetach"]