FROM eclipse-temurin:17-jdk

RUN apt-get update && \
    apt-get install -y unzip zip findutils && \
    rm -rf /var/lib/apt/lists/*

COPY dev/pubCert.crt /tmp/pubCert.crt

RUN keytool -importcert \
    -alias pubCert \
    -file /tmp/pubCert.crt \
    -storepass changeit \
    -keystore $JAVA_HOME/lib/security/cacerts \
    -trustcacerts \
    -noprompt

RUN rm /tmp/pubCert.crt